//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arduino_Temperature.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arduino_Temperature.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;Temperatur im Container&lt;/Title&gt;
        ///&lt;Head&gt;Temperatur im Container (BIMIs Platz)&lt;/Head&gt;
        ///&lt;Body&gt;
        ///&lt;h2&gt;
        ///&amp;TEMP1
        ///&lt;/h2&gt;
        ///&lt;/br&gt;
        ///&lt;/br&gt;
        ///&lt;h2&gt;
        ///&amp;TEMP2
        ///&lt;/h2&gt;
        ///&lt;/br&gt;
        ///&lt;/br&gt;
        ///&lt;h5&gt;
        ///Der Hitzeindex (HI) ist eine in Einheiten der Temperatur angegebene Gr&amp;ouml;&amp;szlig;e zur Beschreibung der gef&amp;uuml;hlten Temperatur auf Basis der gemessenen         ///
        ///Lufttemperatur.
        ///&lt;/h5&gt;
        ///&lt;h4&gt;
        ///&amp;LASTUPDATE
        ///&lt;/br&gt;
        ///&lt;FORM&gt;
        ///&lt;input type=&quot;button&quot; onClick=&quot;location.reload()&quot; value=&quot;Refresh&quot;&gt;
        ///&lt;/FORM&gt;
        ///&lt;/br&gt;
        ///&lt;/br&gt;
        ///&lt;/br&gt;
        ///Gemessen mit einem DH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html_temperature_main_template {
            get {
                return ResourceManager.GetString("html_temperature_main_template", resourceCulture);
            }
        }
    }
}
