//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://skidata.com/tdi/common/v1/data", ClrNamespace = "skidata.com.tdi.common.v1.data")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://skidata.com/tdi/ca/v1/data", ClrNamespace = "skidata.com.tdi.ca.v1.data")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://skidata.com/tdi/ca/v1/msgs", ClrNamespace = "skidata.com.tdi.ca.v1.msgs")]

namespace skidata.com.tdi.common.v1.data
{
    using System.Runtime.Serialization;
    using System.Xml.Linq;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AuthenticationHeader", Namespace = "http://skidata.com/tdi/common/v1/data")]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string UserNameField;

        private string PasswordField;

        private string ApiKeyField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 1)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false, Order = 2)]
        public string ApiKey
        {
            get
            {
                return this.ApiKeyField;
            }
            set
            {
                this.ApiKeyField = value;
            }
        }
    }
}
namespace skidata.com.tdi.ca.v1.data
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SystemVersion", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public partial class SystemVersion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MajorVersionField;

        private string MinorVersionField;

        private string MicroVersionField;

        private string ServiceNameField;

        private System.DateTime SystemDateField;

        private string SystemNameField;

        private string SystemVersionMemberField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string MajorVersion
        {
            get
            {
                return this.MajorVersionField;
            }
            set
            {
                this.MajorVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string MinorVersion
        {
            get
            {
                return this.MinorVersionField;
            }
            set
            {
                this.MinorVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string MicroVersion
        {
            get
            {
                return this.MicroVersionField;
            }
            set
            {
                this.MicroVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.DateTime SystemDate
        {
            get
            {
                return this.SystemDateField;
            }
            set
            {
                this.SystemDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string SystemName
        {
            get
            {
                return this.SystemNameField;
            }
            set
            {
                this.SystemNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Name = "SystemVersion", EmitDefaultValue = false, Order = 6)]
        public string SystemVersionMember
        {
            get
            {
                return this.SystemVersionMemberField;
            }
            set
            {
                this.SystemVersionMemberField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "PaymentTransactionDataList", Namespace = "http://skidata.com/tdi/ca/v1/data", ItemName = "PaymentTransactionData")]
    public class PaymentTransactionDataList : System.Collections.Generic.List<skidata.com.tdi.ca.v1.data.PaymentTransactionData>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaymentTransactionData", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public partial class PaymentTransactionData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string PaymentTransactionNumberField;

        private string OrderTransactionGUIDField;

        private string ParkingTransactionNumberField;

        private string ParkingTransactionGUIDField;

        private skidata.com.tdi.ca.v1.data.PaymentTransactionType PaymentTransactionTypeField;

        private skidata.com.tdi.ca.v1.data.CommonInformation ParkingCommonInformationField;

        private skidata.com.tdi.ca.v1.data.Money PriceField;

        private skidata.com.tdi.ca.v1.data.Money TurnoverField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string PaymentTransactionNumber
        {
            get
            {
                return this.PaymentTransactionNumberField;
            }
            set
            {
                this.PaymentTransactionNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string OrderTransactionGUID
        {
            get
            {
                return this.OrderTransactionGUIDField;
            }
            set
            {
                this.OrderTransactionGUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string ParkingTransactionNumber
        {
            get
            {
                return this.ParkingTransactionNumberField;
            }
            set
            {
                this.ParkingTransactionNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string ParkingTransactionGUID
        {
            get
            {
                return this.ParkingTransactionGUIDField;
            }
            set
            {
                this.ParkingTransactionGUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public skidata.com.tdi.ca.v1.data.PaymentTransactionType PaymentTransactionType
        {
            get
            {
                return this.PaymentTransactionTypeField;
            }
            set
            {
                this.PaymentTransactionTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public skidata.com.tdi.ca.v1.data.CommonInformation ParkingCommonInformation
        {
            get
            {
                return this.ParkingCommonInformationField;
            }
            set
            {
                this.ParkingCommonInformationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public skidata.com.tdi.ca.v1.data.Money Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public skidata.com.tdi.ca.v1.data.Money Turnover
        {
            get
            {
                return this.TurnoverField;
            }
            set
            {
                this.TurnoverField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CommonInformation", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public partial class CommonInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private skidata.com.tdi.ca.v1.data.IdentificationList IdentificationsField;

        private int FacilityNumberField;

        private string FacilityNameField;

        private int CarParkNumberField;

        private string CarParkNameField;

        private int DeviceNumberField;

        private string DeviceNameField;

        private int ArticleNumberField;

        private string ArticleNameField;

        private System.DateTime TimestampField;

        private string ParkingDurationField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public skidata.com.tdi.ca.v1.data.IdentificationList Identifications
        {
            get
            {
                return this.IdentificationsField;
            }
            set
            {
                this.IdentificationsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int FacilityNumber
        {
            get
            {
                return this.FacilityNumberField;
            }
            set
            {
                this.FacilityNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string FacilityName
        {
            get
            {
                return this.FacilityNameField;
            }
            set
            {
                this.FacilityNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public int CarParkNumber
        {
            get
            {
                return this.CarParkNumberField;
            }
            set
            {
                this.CarParkNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string CarParkName
        {
            get
            {
                return this.CarParkNameField;
            }
            set
            {
                this.CarParkNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public int DeviceNumber
        {
            get
            {
                return this.DeviceNumberField;
            }
            set
            {
                this.DeviceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string DeviceName
        {
            get
            {
                return this.DeviceNameField;
            }
            set
            {
                this.DeviceNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public int ArticleNumber
        {
            get
            {
                return this.ArticleNumberField;
            }
            set
            {
                this.ArticleNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string ArticleName
        {
            get
            {
                return this.ArticleNameField;
            }
            set
            {
                this.ArticleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string ParkingDuration
        {
            get
            {
                return this.ParkingDurationField;
            }
            set
            {
                this.ParkingDurationField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Money", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public partial class Money : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CurrencyField;

        private decimal ValueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaymentTransactionType", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public enum PaymentTransactionType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payment = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TopUpPayment = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "IdentificationList", Namespace = "http://skidata.com/tdi/ca/v1/data", ItemName = "Identification")]
    public class IdentificationList : System.Collections.Generic.List<skidata.com.tdi.ca.v1.data.Identification>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Identification", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.data.GenericIdentification))]
    public partial class Identification : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GenericIdentification", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public partial class GenericIdentification : skidata.com.tdi.ca.v1.data.Identification
    {

        private string IdentificatorField;

        private string TypeField;

        private string SubTypeField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Identificator
        {
            get
            {
                return this.IdentificatorField;
            }
            set
            {
                this.IdentificatorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string SubType
        {
            get
            {
                return this.SubTypeField;
            }
            set
            {
                this.SubTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ParkingTransactionDataList", Namespace = "http://skidata.com/tdi/ca/v1/data", ItemName = "ParkingTransactionData")]
    public class ParkingTransactionDataList : System.Collections.Generic.List<skidata.com.tdi.ca.v1.data.ParkingTransactionData>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParkingTransactionData", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public partial class ParkingTransactionData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ParkingTransactionNumberField;

        private string ParkingTransactionGUIDField;

        private skidata.com.tdi.ca.v1.data.ParkingTransactionType ParkingTransactionTypeField;

        private skidata.com.tdi.ca.v1.data.CommonInformation ParkingCommonInformationField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string ParkingTransactionNumber
        {
            get
            {
                return this.ParkingTransactionNumberField;
            }
            set
            {
                this.ParkingTransactionNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string ParkingTransactionGUID
        {
            get
            {
                return this.ParkingTransactionGUIDField;
            }
            set
            {
                this.ParkingTransactionGUIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public skidata.com.tdi.ca.v1.data.ParkingTransactionType ParkingTransactionType
        {
            get
            {
                return this.ParkingTransactionTypeField;
            }
            set
            {
                this.ParkingTransactionTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public skidata.com.tdi.ca.v1.data.CommonInformation ParkingCommonInformation
        {
            get
            {
                return this.ParkingCommonInformationField;
            }
            set
            {
                this.ParkingCommonInformationField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParkingTransactionType", Namespace = "http://skidata.com/tdi/ca/v1/data")]
    public enum ParkingTransactionType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Entry = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exit = 2,
    }
}
namespace skidata.com.tdi.ca.v1.msgs
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TicketDataFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.InternalServiceFailureInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.IllegalDatacarrierFaultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.IllegalUrlFaultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.NoSuchPageNumberFaultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.InvalidParameterFaultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.InvalidApiKeyFaultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(skidata.com.tdi.ca.v1.msgs.CallLimitExceededFaultInfo))]
    public partial class TicketDataFaultInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InternalServiceFailureInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class InternalServiceFailureInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IllegalDatacarrierFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class IllegalDatacarrierFaultInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {

        private string DatacarrierField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string Datacarrier
        {
            get
            {
                return this.DatacarrierField;
            }
            set
            {
                this.DatacarrierField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IllegalUrlFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class IllegalUrlFaultInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {

        private string UrlField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NoSuchPageNumberFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class NoSuchPageNumberFaultInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {

        private int PageField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Page
        {
            get
            {
                return this.PageField;
            }
            set
            {
                this.PageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InvalidParameterFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class InvalidParameterFaultInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {

        private string NameField;

        private string ValueField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, EmitDefaultValue = false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InvalidApiKeyFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class InvalidApiKeyFaultInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CallLimitExceededFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    public partial class CallLimitExceededFaultInfo : skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://skidata.com/tdi/ca/v1", ConfigurationName = "CarAccessTransactionEventInterface")]
public interface CarAccessTransactionEventInterface
{

    // CODEGEN: Generating message contract since the wrapper namespace (http://skidata.com/tdi/ca/v1/msgs) of message GetVersionRequest does not match the default value (http://skidata.com/tdi/ca/v1)
    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/GetVersion", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo), Action = "http://skidata.com/tdi/ca/v1/GetVersion", Name = "TicketDataFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    GetVersionResponse GetVersion(GetVersionRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/GetVersion", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetVersionResponse> GetVersionAsync(GetVersionRequest request);

    // CODEGEN: Generating message contract since the wrapper namespace (http://skidata.com/tdi/ca/v1/msgs) of message NotifyPaymentTransactionRequest does not match the default value (http://skidata.com/tdi/ca/v1)
    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/NotifyPaymentTransaction", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo), Action = "http://skidata.com/tdi/ca/v1/NotifyPaymentTransaction", Name = "TicketDataFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    NotifyPaymentTransactionResponse NotifyPaymentTransaction(NotifyPaymentTransactionRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/NotifyPaymentTransaction", ReplyAction = "*")]
    System.Threading.Tasks.Task<NotifyPaymentTransactionResponse> NotifyPaymentTransactionAsync(NotifyPaymentTransactionRequest request);

    // CODEGEN: Generating message contract since the wrapper namespace (http://skidata.com/tdi/ca/v1/msgs) of message NotifyParkingTransactionRequest does not match the default value (http://skidata.com/tdi/ca/v1)
    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/NotifyParkingTransaction", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo), Action = "http://skidata.com/tdi/ca/v1/NotifyParkingTransaction", Name = "TicketDataFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    NotifyParkingTransactionResponse NotifyParkingTransaction(NotifyParkingTransactionRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/NotifyParkingTransaction", ReplyAction = "*")]
    System.Threading.Tasks.Task<NotifyParkingTransactionResponse> NotifyParkingTransactionAsync(NotifyParkingTransactionRequest request);

    // CODEGEN: Generating message contract since the wrapper namespace (http://skidata.com/tdi/ca/v1/msgs) of message KeepAliveRequest does not match the default value (http://skidata.com/tdi/ca/v1)
    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/KeepAlive", ReplyAction = "*")]
    [System.ServiceModel.FaultContractAttribute(typeof(skidata.com.tdi.ca.v1.msgs.TicketDataFaultInfo), Action = "http://skidata.com/tdi/ca/v1/KeepAlive", Name = "TicketDataFaultInfo", Namespace = "http://skidata.com/tdi/ca/v1/msgs")]
    KeepAliveResponse KeepAlive(KeepAliveRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://skidata.com/tdi/ca/v1/KeepAlive", ReplyAction = "*")]
    System.Threading.Tasks.Task<KeepAliveResponse> KeepAliveAsync(KeepAliveRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetVersion", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class GetVersionRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader;

    public GetVersionRequest()
    {
    }

    public GetVersionRequest(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader)
    {
        this.AuthenticationHeader = AuthenticationHeader;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetVersionResponse", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class GetVersionResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public skidata.com.tdi.ca.v1.data.SystemVersion SystemVersion;

    public GetVersionResponse()
    {
    }

    public GetVersionResponse(skidata.com.tdi.ca.v1.data.SystemVersion SystemVersion)
    {
        this.SystemVersion = SystemVersion;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "NotifyPaymentTransaction", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class NotifyPaymentTransactionRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 1)]
    public skidata.com.tdi.ca.v1.data.PaymentTransactionDataList PaymentTransactionData;

    public NotifyPaymentTransactionRequest()
    {
    }

    public NotifyPaymentTransactionRequest(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader, skidata.com.tdi.ca.v1.data.PaymentTransactionDataList PaymentTransactionData)
    {
        this.AuthenticationHeader = AuthenticationHeader;
        this.PaymentTransactionData = PaymentTransactionData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "NotifyPaymentTransactionResponse", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class NotifyPaymentTransactionResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public bool Result;

    public NotifyPaymentTransactionResponse()
    {
    }

    public NotifyPaymentTransactionResponse(bool Result)
    {
        this.Result = Result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "NotifyParkingTransaction", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class NotifyParkingTransactionRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 1)]
    public skidata.com.tdi.ca.v1.data.ParkingTransactionDataList ParkingTransactionData;

    public NotifyParkingTransactionRequest()
    {
    }

    public NotifyParkingTransactionRequest(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader, skidata.com.tdi.ca.v1.data.ParkingTransactionDataList ParkingTransactionData)
    {
        this.AuthenticationHeader = AuthenticationHeader;
        this.ParkingTransactionData = ParkingTransactionData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "NotifyParkingTransactionResponse", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class NotifyParkingTransactionResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public bool Result;

    public NotifyParkingTransactionResponse()
    {
    }

    public NotifyParkingTransactionResponse(bool Result)
    {
        this.Result = Result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "KeepAlive", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class KeepAliveRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader;

    public KeepAliveRequest()
    {
    }

    public KeepAliveRequest(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader)
    {
        this.AuthenticationHeader = AuthenticationHeader;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "KeepAliveResponse", WrapperNamespace = "http://skidata.com/tdi/ca/v1/msgs", IsWrapped = true)]
public partial class KeepAliveResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://skidata.com/tdi/ca/v1/msgs", Order = 0)]
    public bool KeepAliveSignal;

    public KeepAliveResponse()
    {
    }

    public KeepAliveResponse(bool KeepAliveSignal)
    {
        this.KeepAliveSignal = KeepAliveSignal;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CarAccessTransactionEventInterfaceChannel : CarAccessTransactionEventInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CarAccessTransactionEventInterfaceClient : System.ServiceModel.ClientBase<CarAccessTransactionEventInterface>, CarAccessTransactionEventInterface
{

    public CarAccessTransactionEventInterfaceClient()
    {
    }

    public CarAccessTransactionEventInterfaceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public CarAccessTransactionEventInterfaceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public CarAccessTransactionEventInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public CarAccessTransactionEventInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetVersionResponse CarAccessTransactionEventInterface.GetVersion(GetVersionRequest request)
    {
        return base.Channel.GetVersion(request);
    }

    public skidata.com.tdi.ca.v1.data.SystemVersion GetVersion(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader)
    {
        GetVersionRequest inValue = new GetVersionRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        GetVersionResponse retVal = ((CarAccessTransactionEventInterface)(this)).GetVersion(inValue);
        return retVal.SystemVersion;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetVersionResponse> CarAccessTransactionEventInterface.GetVersionAsync(GetVersionRequest request)
    {
        return base.Channel.GetVersionAsync(request);
    }

    public System.Threading.Tasks.Task<GetVersionResponse> GetVersionAsync(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader)
    {
        GetVersionRequest inValue = new GetVersionRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        return ((CarAccessTransactionEventInterface)(this)).GetVersionAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    NotifyPaymentTransactionResponse CarAccessTransactionEventInterface.NotifyPaymentTransaction(NotifyPaymentTransactionRequest request)
    {
        return base.Channel.NotifyPaymentTransaction(request);
    }

    public bool NotifyPaymentTransaction(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader, skidata.com.tdi.ca.v1.data.PaymentTransactionDataList PaymentTransactionData)
    {
        NotifyPaymentTransactionRequest inValue = new NotifyPaymentTransactionRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        inValue.PaymentTransactionData = PaymentTransactionData;
        NotifyPaymentTransactionResponse retVal = ((CarAccessTransactionEventInterface)(this)).NotifyPaymentTransaction(inValue);
        return retVal.Result;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<NotifyPaymentTransactionResponse> CarAccessTransactionEventInterface.NotifyPaymentTransactionAsync(NotifyPaymentTransactionRequest request)
    {
        return base.Channel.NotifyPaymentTransactionAsync(request);
    }

    public System.Threading.Tasks.Task<NotifyPaymentTransactionResponse> NotifyPaymentTransactionAsync(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader, skidata.com.tdi.ca.v1.data.PaymentTransactionDataList PaymentTransactionData)
    {
        NotifyPaymentTransactionRequest inValue = new NotifyPaymentTransactionRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        inValue.PaymentTransactionData = PaymentTransactionData;
        return ((CarAccessTransactionEventInterface)(this)).NotifyPaymentTransactionAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    NotifyParkingTransactionResponse CarAccessTransactionEventInterface.NotifyParkingTransaction(NotifyParkingTransactionRequest request)
    {
        return base.Channel.NotifyParkingTransaction(request);
    }

    public bool NotifyParkingTransaction(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader, skidata.com.tdi.ca.v1.data.ParkingTransactionDataList ParkingTransactionData)
    {
        NotifyParkingTransactionRequest inValue = new NotifyParkingTransactionRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        inValue.ParkingTransactionData = ParkingTransactionData;
        NotifyParkingTransactionResponse retVal = ((CarAccessTransactionEventInterface)(this)).NotifyParkingTransaction(inValue);
        return retVal.Result;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<NotifyParkingTransactionResponse> CarAccessTransactionEventInterface.NotifyParkingTransactionAsync(NotifyParkingTransactionRequest request)
    {
        return base.Channel.NotifyParkingTransactionAsync(request);
    }

    public System.Threading.Tasks.Task<NotifyParkingTransactionResponse> NotifyParkingTransactionAsync(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader, skidata.com.tdi.ca.v1.data.ParkingTransactionDataList ParkingTransactionData)
    {
        NotifyParkingTransactionRequest inValue = new NotifyParkingTransactionRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        inValue.ParkingTransactionData = ParkingTransactionData;
        return ((CarAccessTransactionEventInterface)(this)).NotifyParkingTransactionAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    KeepAliveResponse CarAccessTransactionEventInterface.KeepAlive(KeepAliveRequest request)
    {
        return base.Channel.KeepAlive(request);
    }

    public bool KeepAlive(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader)
    {
        KeepAliveRequest inValue = new KeepAliveRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        KeepAliveResponse retVal = ((CarAccessTransactionEventInterface)(this)).KeepAlive(inValue);
        return retVal.KeepAliveSignal;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<KeepAliveResponse> CarAccessTransactionEventInterface.KeepAliveAsync(KeepAliveRequest request)
    {
        return base.Channel.KeepAliveAsync(request);
    }

    public System.Threading.Tasks.Task<KeepAliveResponse> KeepAliveAsync(skidata.com.tdi.common.v1.data.AuthenticationHeader AuthenticationHeader)
    {
        KeepAliveRequest inValue = new KeepAliveRequest();
        inValue.AuthenticationHeader = AuthenticationHeader;
        return ((CarAccessTransactionEventInterface)(this)).KeepAliveAsync(inValue);
    }
}
